import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/providers";
import Navbar1 from "@/components/Navbar1/Navbar1";
import Navbar2 from "@/components/Navbar2/Navbar2";
import LogRegButtons from "@/components/LogRegButtons/LogRegButtons";
import { ApolloProvider } from "@apollo/client";
import client from "@/queries/apolloClient";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nexo TV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ApolloProvider client={client}>
        <Providers>
          <LogRegButtons/>
          <Navbar2 />
          {children}
        </Providers>
        </ApolloProvider>
      </body>
    </html>
  );
}
